Icinga/icingaweb2-module-director

- library/Director/PropertyModifier/PropertyModifierMap.php
Return the data list name instead of the id for the function
getDatalistName().
refs #621
> Return data list name

- doc/15-Service-apply-for-example.md
- doc/60-CLI.md
- doc/70-REST-API.md
Hi, during reading the documentation, I've spotted some typos. I'd be glad if you could merge this request.
Kind regards,
Bernd
> Documentation typo fixes

- .gitignore
- .travis.yml
- phpcs.xml
- test/bootstrap.php
- test/setup_vendor.sh
Not only for travis, but also for local use.
This is similar to how other modules handle it right now:
* icingaweb2-module-businessprocess
* icingaweb2-module-eventdb
> Update testing scripts and settings

- library/Director/Import/ImportSourceLdap.php
fix typo in ImportSourceLdap -> Properties
> ImportSourceLdap: fix typo

- application/forms/IcingaTemplateChoiceForm.php
workaround/fix for issue #1242
> force use of autoincrement id for generating the SQL query

- doc/10-How-it-works.md
> Correct spelling of "of"

- library/vendor/ipl/Data/SimpleQueryPaginationAdapter.php
Breaks pagination further than page 2.
fixes #1273
> SimpleQueryPaginationAdapter: Fix getOffset interface

- library/Director/Web/Table/ImportedrowsTable.php
Just like ImportsourceHookTable.
refs #1325
> ImportedrowsTable: Render complex data types in pre tag

- library/Director/Field/FieldSpec.php
- library/Director/Hook/HostFieldHook.php
- library/Director/Hook/ServiceFieldHook.php
- library/Director/Web/Form/IcingaObjectFieldLoader.php
Allow creating non editable fields via hook in Director host/service form by registering them in IcingaWeb  modules.
> Allow creating hooks for custom fields in host/service form

- application/locale/de_DE/LC_MESSAGES/director.po
Fix for https://github.com/Icinga/icingaweb2-module-director/issues/1446
see https://www.duden.de/rechtschreibung/Status
> Fix translation Stati -> Status

- library/Director/Core/CoreApi.php
> Import check commands from Core API

- contrib/linux-agent-installer/Icinga2Agent.bash
- contrib/linux-agent-installer/Icinga2AgentHead.bash
- library/Director/IcingaConfig/AgentWizard.php
* Multiple Endpoints
* Default Global Zone is added automatically
* Stable without need for sysconfig
fixes #1585
> Update and improve Linux kickstart script

- schema/mysql-migrations/upgrade_150.sql
- schema/mysql.sql
- schema/pgsql-migrations/upgrade_150.sql
- schema/pgsql.sql
> schema/150: Add constraint from user to period

- library/Director/Objects/IcingaServiceSet.php
This allows the user to preview all sub-service sets.
Normally the preview only shows
1. the applied services
2. when only directly added service-sets it is empty
> IcingaServiceSet: Render sub-sets in config preview

- application/forms/IcingaTimePeriodForm.php
- library/Director/Objects/IcingaObject.php
- library/Director/Objects/IcingaObjectMultiRelations.php
- library/Director/Objects/IcingaTimePeriod.php
- schema/mysql-migrations/upgrade_151.sql
- schema/mysql.sql
- schema/pgsql-migrations/upgrade_151.sql
- schema/pgsql.sql
- test/php/library/Director/Objects/IcingaTimePeriodTest.php
> Add support for Timeperiod include/exclude

- library/Director/Objects/GroupMembershipResolver.php
- library/Director/Objects/IcingaObject.php
- library/Director/Objects/ObjectApplyMatches.php
- library/Director/Repository/IcingaTemplateRepository.php
- library/Director/Repository/RepositoryByObjectHelper.php
- library/Director/Resolver/TemplateTree.php
* Fixing static resolving in general
* Avoiding a problem where apply were matched when assign_filter is an
empty string (empty FilterAnd)
* Adapt to ResolverTest
fixes #1574
> GroupMembershipResolver: Fix issues with apply and static assignments

- .travis.yml
- test/travis-prepare.sh
> travis: Split phpcs to a single matrix element

- application/clicommands/HousekeepingCommand.php
- library/Director/Db/HostMembershipHousekeeping.php
- library/Director/Db/Housekeeping.php
- library/Director/Db/MembershipHousekeeping.php
- library/Director/Objects/GroupMembershipResolver.php
- library/Director/Test/BaseTestCase.php
- test/php/library/Director/Objects/HostGroupMembershipResolverTest.php
This is a feature in addition to #1618
> Add group apply housekeeping and testing

- library/Director/Objects/IcingaObject.php
> fix gettype for multiple host selection

- .travis.yml
- application/controllers/DataController.php
- library/Director/Web/Controller/ObjectsController.php
- test/setup_vendor.sh
> ci: Update travis matrix and vendor test helpers

- library/Director/Import/Import.php
> Import: Improve exception info during storing rows

- library/Director/PropertyModifier/PropertyModifierParseURL.php
- run.php
- test/php/library/Director/PropertyModifier/PropertyModifierParseURLTest.php
Provide a PropertyModifier for the PHP function parse_url().
I have a lot of websites that I need to monitor which come from different sources. This PropertyModifier is quite handy for me. Maybe also for others?
> Add PropertyModifierParseURL.

- library/Director/Objects/IcingaService.php
So that it redirects back to services of this serviceset.
> IcingaService: Fix getOnDeleteUrl() for service sets

- application/controllers/SuggestController.php
- application/forms/IcingaCloneObjectForm.php
Similar to the implementation for Service Set.
> Allow IcingaService to be cloned to a different host

- library/Director/Objects/IcingaArguments.php
Icinga 2 will still not dump this, but in Director Baskets it is included.
> IcingaArguments: Import Icinga DSL in arguments when available from baskets

- application/forms/IcingaScheduledDowntimeForm.php
- library/Director/Objects/IcingaScheduledDowntime.php
- schema/mysql-migrations/upgrade_162.sql
- schema/mysql.sql
- schema/pgsql-migrations/upgrade_162.sql
- schema/pgsql.sql
schema, form, rendering
fixes #1831
> ScheduledDowntimes: Hosts with Services, optional

- application/forms/IcingaServiceGroupForm.php
> ServiceGroup: Make assign optional

- doc/30-Configuration-Baskets.md
I wrote a file with some example documentation for the new Configuration Baskets feature.  If it's useful to you all, feel free to include it, with modifications if you like.
> Add documentation for configuration baskets

- library/Director/Data/AssignFilterHelper.php
- library/Director/Objects/ObjectApplyMatches.php
- library/Director/Web/Table/ApplyRulesTable.php
- library/Director/Web/Table/IcingaHostAppliedServicesTable.php
- test/php/library/Director/Data/AssignFilterHelperTest.php
> Implement AssignFilterHelper to improve apply/assign matching

- library/Director/Web/Table/IcingaHostAppliedServicesTable.php
fixes #1862 
list of applied services are sorted with this change
> Sort list of applied services by object_name

- library/Director/Web/Controller/TemplateController.php
fixes #1864 
Tested with host links in the hosts based on host templates view and service apply rules
> Fix wrong links for hosts/apply rules based on <something>

- library/Director/Web/Controller/ObjectsController.php
This fixes issue #1881 
I'm not sure if this causes any regressions. (I didn't notice one)
> Fix ambiguous host_id field

- library/Director/Web/Controller/ObjectsController.php
> Allow Download as JSON for service apply rules and templates

- application/clicommands/ImportsourceCommand.php
> CLI: Apply modifiers in 'importsource fetch'

- contrib/linux-agent-installer/Icinga2Agent.bash
> Fix version detection in the Linux kickstart for Icinga 2.11

- contrib/windows-agent-installer/Icinga2Agent.psm1
Updated Windows Agent installer script to the latest available version
> Updated Windows Agent installer script

- contrib/windows-agent-installer/Icinga2Agent.psm1
> Fixes broken default global zones config

- doc/02-Installation.md
Missing close single quote in Mysql example for password
> Missing single quote in mysql example

- contrib/linux-agent-installer/Icinga2Agent.bash
I wondered why the agent script, that director generates for my hosts, doesnt run on my alpine linux machines, so i modified the agent script template, for compatibility with alpine linux.
I tested this on a alpine linux system in my personal infrastructure and it worked perfect.
It would be really nice, if you could review my changes and merge my improved template.
> Add agent script support for Alpine Linux

- public/css/module.less
> Make 50:50 layout working with the flexbox layout

- schema/mysql-migrations/upgrade_175.sql
- schema/mysql.sql
It's a keyword on MySQL 8 now. (https://dev.mysql.com/doc/refman/8.0/en/keywords.html)
> schema: Quote keyword `groups`

- library/Director/Web/SelfService.php
- public/css/module.less
> Remove css styles from php code

- library/Director/Objects/DirectorDatalist.php
Deletion of data lists which are used in icinga objects through custom variables is prevented. As the objects that use these data lists could not be restored through snapshots otherwise.
[ref/IP/37953](https://rt.icinga.com/Ticket/Display.html?id=37953)
> Prevent deletion of data lists that are in use.

- public/css/module.less
> Add dark mode themes support

- library/Director/Web/Table/IcingaServiceSetServiceTable.php
> Strikethrough deactivated services in applied service set

- library/Director/IcingaConfig/AgentWizard.php
- library/Director/Web/SelfService.php
Remove the PowerShell module in Agents tab and change the install script for Icinga for windows.
fixes [ref/IP/43483](https://rt.icinga.com/Ticket/Display.html?id=43483)
> Change the install script for Icinga for Windows

- schema/pgsql-migrations/upgrade_187.sql
> migrations: fix syntax error on 187

- application/controllers/HostController.php
fixes [ref/IP/47505](https://rt.icinga.com/Ticket/Display.html?id=47505)
> Remove limit count for service set directly added to the host

- doc/82-Changelog.md
- library/Director/Objects/IcingaObjectGroup.php
> IcingaObjectGroup: no membership refresh w/o assign

- library/Director/Web/Form/QuickForm.php
> QuickForm: Backport the CSRF validation in master

- library/Director/Import/ImportSourceRestApi.php
> ImportSourceRestApi: Fix strlen deprecation

- library/Director/Objects/DirectorDatalist.php
> DirectorDatalist: Match column types to join tables in postgres by explicit type casting

- application/forms/ImportRowModifierForm.php
> ImportRowModifierForm: Fix removal of filter expression

- library/Director/ProvidedHook/Icingadb/CustomVarRenderer.php
- library/Director/ProvidedHook/Monitoring/CustomVarRenderer.php
> CustomVarRenderer: Fix custom var renderer for apply-for-rules

- library/Director/ProvidedHook/Icingadb/CustomVarRenderer.php
- library/Director/ProvidedHook/Monitoring/CustomVarRenderer.php
> CustomVarRenderer: Fix illegal offset error if the value is an array

- application/forms/IcingaAddServiceForm.php
> Check if service templates exist to add services
