- library/Director/Web/Table/QuickTable.php
We need to use the result of andFilter() as the new Filter.
The filter gets replaced by FilterAnd($oldFilter, $enforcedFilter) here.
Please also cherry-pick in 1.3.x
> QuickTable: Fix enforced filters for non-FilterAnd filters

- library/Director/Import/Sync.php
- library/Director/Objects/SyncRule.php
- library/Director/Test/ImportSourceDummy.php
- library/Director/Test/SyncTest.php
- schema/pgsql-migrations/upgrade_142.sql
- schema/pgsql.sql
- test/php/library/Director/Import/HostSyncTest.php
So that you can filter by fields not used in properties, or in property filters.
fixes #1130
refs #876 
Also fixes #1141 for tests
> Sync: Respect the fields used in filter_expression of the SyncRule

- library/Director/Web/Table/DependencyTemplateUsageTable.php
the usage table for dependency templates is missing so i've just added them :wink:
> Dependencies: add usage overview and table

- library/Director/Web/Controller/ObjectController.php
This can happen whenever the deployment related config of Zones,
Endpoints or ApiUsers is incomplete or missing.
This should not break forms needed to fix the problem.
> ObjectController: Don't let DeploymentLink break the interface on errors

- doc/60-CLI.md
There was an copy&paste error in the health check documentation
I added another example with the short form of the check just in case we need the short form for the ITL integration.
> fix a copy&paste error in health check documentation

- library/Director/ProvidedHook/Monitoring/ServiceActions.php
Not only services of hosts managed by Director. This aligns behavior
with HostActions itself.
> ServiceActions: Show inspect link on all services

- library/Director/Web/Table/DbHelper.php
- library/Director/Web/Table/DeploymentLogTable.php
- library/Director/Web/Widget/IcingaObjectInspection.php
This adapts behavior from DeploymentLogTable
fixes #1420
> IcingaObjectInspection: Properly read and handle config_checksum

- library/Director/PropertyModifier/PropertyModifierMakeBoolean.php
This bug is also present in support/1.3 and support/1.4, but I'm not sure what the merging policy is for those. I can rebase to either of those if needed, or file separate pull requests.
> Fix settings name in PropertyModifierMakeBoolean.

- library/vendor/ipl/Web/Table/QueryBasedTable.php
PHP 7.2 is stricter about invoking count() with parameters which
are not countable:
https://secure.php.net/manual/en/migration72.incompatible.php
This case is triggered in QueryBasedTable, for example when reviewing
the Activity Log:
count(): Parameter must be an array or an object that implements Countable (QueryBasedTable.php:115)
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'count(): Parame...', '/usr/share/icin...', 115, Array)
#1 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(115): count(NULL)
#2 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Web\Table\QueryBasedTable->renderContent()
#3 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/H …
> PHP 7.2 compatibility: Avoid failing when attempting to render NULL column-set

- library/vendor/php-diff/SOURCE
- library/vendor/php-diff/lib/Diff/Renderer/Html/Array.php
- library/vendor/php-diff/lib/Diff/Renderer/Html/Inline.php
- library/vendor/php-diff/lib/Diff/SequenceMatcher.php
Apply upstream fixes for php-diff, as well as a fix for PHP 7.2 (upstream pull request open, at https://github.com/chrisboulton/php-diff/pull/50)
---
Version is based on:
* https://github.com/chrisboulton/php-diff/commit/3cb3f7ce6bb8b910f5a41ea1887b1faceba6a7d7
* and https://github.com/chrisboulton/php-diff/pull/50
> Upstream fixes for php-diff

- application/controllers/SyncruleController.php
- application/forms/SyncCheckForm.php
- application/forms/SyncRunForm.php
- library/Director/Import/Sync.php
- library/Director/Objects/GroupMembershipResolver.php
- library/Director/Objects/ObjectApplyMatches.php
This addresses multiple problems in Sync and GroupMembershipResolver.
> Improve performance of sync

- library/Director/Import/Sync.php
So DatalistEntry can be synced
fixes #1048
> Sync: Only prefetch relations for IcingaObject

- library/vendor/php-diff/SOURCE
- library/vendor/php-diff/lib/Diff/Renderer/Html/Array.php
See https://github.com/chrisboulton/php-diff/pull/51
> php-diff: Fix undefined offset in Array Renderer

- library/Director/IcingaConfig/IcingaConfig.php
This hasn't been used since Director doesn't set execution methods for commands anymore.
Code cleanup deluxe...
> IcingaConfig: Remove library import from generated config

- application/forms/IcingaDependencyForm.php
I'd like to propose this small change to "Dependencies", which allows users to force a Dependency into a specific zone.  This is useful when someone wants to create a dependency between an object in one zone to an object in a parent zone.  If the Dependency apply rule is defined in the global zone (current behaviour), an Endpoint in the child zone may try to apply the dependency to its object, but will throw an error because it does not know about the parent object in another zone.  Forcing the Dependency only to deploy to the parent zone fixes that problem.
> add Zone option to Dependency Form

- application/controllers/SuggestController.php
- application/views/helpers/FormDataFilter.php
- library/Director/Web/Form/IplElement/ExtensibleSetElement.php
- public/css/module.less
- public/js/module.js
Variables that have a datalist behind should be able to list suggestions.
This PR adds the appropriate suggestion lookup for all vars that are based on a datalist.
ref/NC/565994
> Add input suggestion for datalist vars

- library/Director/Objects/IcingaObjectGroups.php
"doesn't exists" -> "doesn't exist"
> Typo in IcingaObjectGroups.php

- application/controllers/CommandController.php
I'd like to propose this quick fix for an issue that has come up when adding new commands via the API.  The operation will return with an error message tagged on that says : "message":"Uncaught Error: Call to a member function isInUse() on null in....CommandController.php"  The command is added, but this error message comes back and makes the json response invalid.
The fix just skips the "showUsage()" function call for API requests (I believe that is meant for the human interface only).
> make call to showUsage conditional on whether request is an API request

- library/Director/IcingaConfig/IcingaConfig.php
try / except was never needed there, because get_host should never
throw an exception. It will be null then.
fixes #1610
Introduced by:
* fd372c6b6286f9d8e7fbe1c9dead719bc5127790
* bf68dbcaca0a8dc85c8427042a3012cd482ff225
> IcingaConfig: Avoid try/except for compatibility with Icinga >= 2.6

- library/Director/IcingaConfig/IcingaConfig.php
globals[key] works, although it wasn't documented how it
behaves in the case when this field doesn't exist.
Previously this has been a dictionary which silently returns
null if the key doesn't exist. With v2.10, globals turned
into a namespace which throws an error if not existing (which is
the correct behaviour).
In order to avoid configuration errors with 2.10, this is changed
into `contains()` which has been sitting in dictionaries since 2014.
So this patch ensures compatibility with older versions as well.
> Render Icinga config helpers with safe globals access

- doc/02-Installation.md
> Enhance installation docs and add release download URL

- application/forms/IcingaAddServiceForm.php
This follows the same principle as with hosts where the URL
already is put into. I've found it more convenient to just
click on it and not having to navigate into the services tree :)
> Add URL to service template creation note

- public/css/module.less
- public/js/module.js
This is a partial revert from:
* 2d802128ac9629dce18d6f1bc2e2a1c308805ff7
* 73a2060b4255be0a8d443ad99290d75901f24d0c
Before:
After:
Todos:
> Revert form description back to inline format

- library/Director/IcingaConfig/IcingaConfigHelper.php
In renderStringWithVariables()
This can happen when variables are stored with an empty string, for an apply rule.
Normally Director won't save empty string variables, it will delete the var instead. But when you set all vars as array via sync.
If a user would have synced this to vars, it was rendered without any quotes.
```json
{
"a": "test",
"b": ""
}
```
Until now:
```
vars.b =
```
Fixed:
```
vars.b = ""
```
> ConfigHelper: Ensure empty vars are not written as void to config

- application/forms/IcingaCommandForm.php
- library/Director/Objects/IcingaCommand.php
- library/Director/Web/ObjectPreview.php
- library/Director/Web/Widget/IcingaObjectInspection.php
- schema/mysql-migrations/upgrade_160.sql
- schema/mysql.sql
- schema/pgsql-migrations/upgrade_160.sql
- schema/pgsql.sql
Icinga 2 allows this from the beginning.
This is needed for migration purposes and old commands.
ref/NC/573707
> IcingaCommand: Allow command to be rendered as string

- library/Director/Objects/IcingaServiceSet.php
This allows service sets to be deleted, including their children sets that
are assigned to hosts.
The UI forbids deleting those sets, but we can use it like this for CLI
and purging during sync.
> IcingaServiceSet: Delete host sets when deleting a set

- library/Director/Web/Table/ImportsourceHookTable.php
Only affects Preview of an ImportSource.
This will make sure applying modifiers before initializing the
ArrayDatasource.
Before this change counting and pagination was broken with Black and
Whitelist.
> Import preview should display data correctly with Black/Whitelisting

- library/Director/Objects/IcingaServiceSet.php
- library/Director/Web/Controller/ObjectController.php
- library/Director/Web/Widget/ActivityLogInfo.php
- Service to Host or ServiceSet
- Set to Host
> Improve ActivityLog for services and servicesets

- library/Director/Db/Cache/PrefetchCache.php
- library/Director/Import/Sync.php
This can happen when using SyncJob with all jobs, or when triggering syncs within the same PHP instance.
We try to reset prefetch cache, but do not purge all of it.
This can cause strange issues on object changes and deletions, that don't appear when handling a single sync.
> Avoid caching between multiple runs of sync

- library/Director/Db/Migrations.php
- schema/mysql-migrations/upgrade_163.sql
- schema/mysql.sql
This migrates all DATETIME to TIMESTAMP in MySQL, so we support timezones and every timestamp can be correctly converted between UTC (storage) and local timezone of the user.
**Only affects MySQL**
Affects the following tables:
* director_activity_log (largest update set)
* director_deployment_log
* director_schema_migration
* director_job
* import_source
* sync_rule
* sync_run
fixes #1332 
fixes #1813
This fix will be released with 1.7.0 and not backported to an earlier version.
If you currently experience problems with timezones, you can apply the schema migration manually like this:
**Make a mysqldump backup before starting with the changes***
```
$ mysql icinga_director
// Set your preferred timezone if you like (important for converting from local to UTC)
// By default: client system …
```
> Ensure MySQL data supports timezones

- application/controllers/HostController.php
- library/Director/IcingaConfig/IcingaConfig.php
- library/Director/Settings.php
Tested with local test environment, a warning is logged in Icinga 2 when used:
```
[2019-04-30 10:36:36 +0000] warning/config: Director: Magic Apply For was used on Host "test1", it is now deprecated and will be removed in Director 1.8.0 (see issue #1850 #1851)
```
fixes #1850
> IcingaConfig: Deprecate magic_apply_for as config feature

- library/Director/Core/CoreApi.php
The director automatically removes uncollected deployments if they're
older than the running one. Deployments are uncollected if Icinga 2 did
not write a status file or startup log (yet). This happens when you
manage to ship a deployment while Icinga 2 is already preparing to
restart with a deployed configuration. It also removes deployments
which were forgotten by Icinga 2 because of bugs in previous versions.
If there are uncollected deployments, the check whether they are older
than the running one is based on string comparison of the deployments'
start time. While this works for MySQL and MariaDB where the output of
timestamps is always ISO, it may fail for PostgreSQL because there the
output format is configurable. If the output format is set to report
the day first, the string …
> pgsql: Fix unexpected removal of current deployment

- doc/10-How-it-works.md
We had some users using `director-global` for syncing their own configuration files. While this is technically possible it's not "best practice" and can produce some side effects. Therefore the warning.
> doc: add a note about director-global being reserved for Director

- application/clicommands/HostgroupsCommand.php
This adds a "icingacli director hostgroups" CLI command for listing hostgroups defined in Icinga Director.
> add "icingacli director hostgroups" CLI command for listing hostgroups

- library/Director/Web/Form/Element/ExtensibleSet.php
In case a user switched from a plain Integer field, to a Datalist field, Extensible set failed with:
```
ExtensibleSet expects to work with Arrays X
```
ref/NC/614217
> ExtensibleSet: Migrate also integers to an array

- public/css/module.less
Starting with Web 2.7.0 the reworked form styles are only available for
for forms with the CSS class icinga-form. Since the Director uses its
own form styles, the styles for form errors no longer apply and thus
look ugly. This commit (re)introduces those rules for the Director.
Before:
After:
> Fix bad looking form errors for Web 2 >= 2.7.0

- application/forms/KickstartForm.php
After importing the sample SQL into Postgres, I get an error message saying the database needs to be set to utf8, when it already is:
In my case, $resourceConfig['charset'] === 'UTF-8'. By adding this to the list of allowed charsets, the error message disappears.
> KickstartForm: add 'UTF-8' to array of allowed charsets, to support Postgres

- application/forms/IcingaCommandArgumentForm.php
This small PR adds a form field to the command argument form that allows the user to add a description to a command argument.
Everything on the API side already seems to be in place and i was able to test it successfully (adding a description to an argument makes it show up in the command preview).
> Add description field to command argument form

- application/forms/DeployConfigForm.php
- application/locale/de_DE/LC_MESSAGES/director.po
Fix the message to use a formal tone as it is being used in a technical context.
https://www.grammarly.com/blog/is-anyways-a-word/
> Fix typo in DeployConfigForm.php

- contrib/linux-agent-installer/Icinga2Agent.bash
CentOS 7:
```
[root@server121 ~]# icinga2 --version 2>/dev/null | grep version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.0-1)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
Platform version: 7 (Core)
Kernel version: 4.4.193-1.el7.elrepo.x86_64
```
Debian 10:
```
root@slde0030 ~ # icinga2 --version 2>/dev/null | grep version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.0-1)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
Platform version: 10 (buster)
Kernel version: 4.19.0-6-amd64
```
At least for CentOS, version is not prepended by "v" or "r".
> Fix icinga_version to detect version without leading v/r

- contrib/linux-agent-installer/Icinga2Agent.bash
It seems as if the version output of the Icinga executable changed.
The current version check searches for "version" whereas Icinga 2.1.1-1 outputs the word capitalized.
I added the `-i` flag to grep to ignore the case there instead of complicating the rexex.
> Fixing linux install script version check

- library/Director/Restriction/HostgroupRestriction.php
Before, for new hosts the code checked whether the host is part of any
restricted hostgroup only if the host's groups got modified directly.
I honestly don't know how that should be possible, since one can't add
host groups directly if restricted.
Now, for new hosts the code checks whether the resolved host groups
match at least one of the restricted host groups.
fixes #2020
> Fix host templates not usable with hostgroup restrictions

- library/Director/Import/ImportSourceRestApi.php
- library/Director/Test/BaseTestCase.php
- test/php/library/Director/Import/ImportSourceRestApiTest.php
Allows a user to add additional headers, e.g. by setting a specific `Accept` or any authentication header.
Also `extract_property` now has a logic for deeper keys like "result.objects", "key.deeper_key.very_deep"
> ImportSourceRestApi: Add header and deeper extract_property

- library/Director/PropertyModifier/PropertyModifierGetHostByAddr.php
Modifier GetHostByAddr fails for some reason the value is null. Instead of failing this will return null.
Depending on PHP version Lowercase requires PHP-mbstring which was not listed as a dependency.
> Fixed: GetHostByAddr: Handle Null

- library/Director/ProvidedHook/Monitoring/HostActions.php
- library/Director/ProvidedHook/Monitoring/ServiceActions.php
Icinga DB Web loads `monitoring`'s action hooks. If there's no backend configured or the module isn't enabled, Director fails if asked for action urls and runs into a fatal error.
* I'd liked to just catch the error, but that's not possible anymore since PHP 8 (`@` doesn't silence fatal errors anymore)
* I considered to provide a fake backend for a moment, but then noticed class `Monitoring` doesn't even ask for one if the module is disabled
* I don't want to patch Director at runtime
Hence, to make the Director work with Icinga DB Web rc2+ this is required.
> Monitoring: Don't fail if module monitoring is not enabled

- library/Director/Objects/IcingaObject.php
IcingaArguments passes the $resolved through to the individual argument in the toPlainObject. There lies the error,
simply pass false - because the argument itself cannot have any parents and therefore cannot be resolved
[ref/IP/36053](https://rt.icinga.com/Ticket/Display.html?id=36053)
> Pass $resolved as False for arguments to toPlainObject()

- library/Director/Objects/IcingaObjectImports.php
The keys of $imports in IcingaObjectImports must be converted to string explicitly or else it establishes incorrect parent-child relation
in icinga_host_inheritance table in case the key is integer value and there is an host object with id = key(integer) icinga_host table.
This results in undefined offset while triggering sync rule.
[ref/IP/36089](https://rt.icinga.com/Ticket/Display.html?id=36089&results=9fd14bd96eccc7871e1fbc5f10bf4b96)
> Convert $imports keys to string explicitly

- library/Director/ProvidedHook/IcingaDbCubeLinks.php
- register-hooks.php
fixes Icinga/icingaweb2-module-cube#64
> Add cube links for objects from Icingadb and register the hook

- application/forms/IcingaScheduledDowntimeRangeForm.php
- application/forms/IcingaTimePeriodRangeForm.php
- application/locale/de_DE/LC_MESSAGES/director.po
- application/locale/it_IT/LC_MESSAGES/director.po
- application/locale/ja_JP/LC_MESSAGES/director.po
Description was unclear about format.
Looks like you are able to build a comma -separated list:
--> monday, tuesday,...
instead of:
--> monday or tuesday or...
> IcingaTimePeriod: make description more clear

- library/Director/Data/ValueFilter/FilterInt.php
- library/Director/Web/Table/QuickTable.php
https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.ctype
> Avoid passing non-string args to `ctype_*()` functions

- library/Director/Objects/IcingaServiceSet.php
The Services which were added into the Service Set after the snapshot was created must be deleted when the Service Set is being restored from the snapshot.
[ref/IP/37937](https://rt.icinga.com/Ticket/Display.html?id=37937)
> Delete newly added Services in Service Set when restoring it from snapshot

- library/Director/Dashboard/Dashlet/NotificationApplyDashlet.php
- library/Director/Dashboard/Dashlet/NotificationsDashlet.php
I believe the `bell` icon is more appropriate for directors use-case since icingaweb seems to use `megaphone` for announcements in "System" > "Announcements":
and `bell` is used in "History":
as far as i understand the icingaweb2 source, as a noob to it, this should make the iconography in the ui more consistent.
> fix: use bell icon for notifications

- library/Director/Objects/SyncRule.php
Icinga director throws error when we try to restore sync rule from snapshot of the configuration basket after its name has been changed.
[ref/IP/37949](https://rt.icinga.com/Ticket/Display.html?id=37949#txn-638589)
> Fix sync rule restore from snapshot on name change

- library/Director/DataType/DataTypeDatalist.php
Before this change, when the value for the data field of data type "Datalist" (and element behaviour is "Extend the list with new values") is blank, then the director throws mysql error for trying to insert a blank entry into data list entry table. 
[ref/IP/33703](https://rt.icinga.com/Ticket/Display.html?id=38958)
> Prevent inserting blank entries for extensible data list.

- library/Director/PropertyModifier/PropertyModifierReplaceNull.php
- register-hooks.php
Because of recent fix of the PropertyModifiers to keep null values, instead of replacing with an empty string, there is no longer an option to replace a null value with a string. 
So @dgoetz helped me create a new PropertyModifier to be used instead. A test was successful. 
Ref/NC/750293
> PropertyModifier: Replace Null with String

- application/forms/IcingaCommandForm.php
- library/Director/Objects/IcingaCommand.php
According to https://github.com/Icinga/icinga2/pull/6055 this feature was removed from Icinga 2.
> IcingaCommand: Remove obsolete CLR check

- library/Director/Data/Db/IcingaObjectQuery.php
Compatibility with earlier versions than 2.11 is still the case. The commits contain further explanations.
> Do not use deprecated web functions

- application/controllers/HostController.php
- library/Director/Web/Table/IcingaServiceSetServiceTable.php
- library/Director/Web/Table/ObjectsTable.php
The limit in ObjectsTable::prepareQuery() limits the number of services shown in HostController::servicesAction. But this limit is required for pagination in ServicesController. Hence, reset the limit when this query is used in HostController::servicesAction().
[ref/IP/42836](https://rt.icinga.com/Ticket/Display.html?id=42836)
> Reset Limit count and offset for `$table` in  HostController::servicesAction

- application/controllers/ServiceController.php
- library/Director/Db/Branch/UuidLookup.php
Backport of 9a0279b111803a362c00f342bacfde775eb865f6 and 4c502bb010dd473289acc177a0b9a29d2af25f42
> Fix calling `toString()` on null

- library/Director/Objects/DirectorJob.php
Remove wrong type casting:
ts_last_attempt: 2022-12-07 21:24:53
ts_last_attempt (with type casting to int): 2022
> fix wrong type casting

- doc/70-REST-API.md
the example uses wrong parameters to get configs and activities, according to the code: https://github.com/Icinga/icingaweb2-module-director/blob/master/application/controllers/ConfigController.php#L144
> fix wrong example in rest-api docs

- library/Director/Db/IcingaObjectFilterHelper.php
- library/Director/Web/Controller/ObjectsController.php
- library/Director/Web/Controller/TemplateController.php
- library/Director/Web/Table/ApplyRulesTable.php
- library/Director/Web/Table/DependencyTemplateUsageTable.php
- library/Director/Web/Table/HostTemplateUsageTable.php
- library/Director/Web/Table/IcingaServiceSetServiceTable.php
- library/Director/Web/Table/NotificationTemplateUsageTable.php
- library/Director/Web/Table/ObjectSetTable.php
- library/Director/Web/Table/ObjectsTable.php
- library/Director/Web/Table/ObjectsTableService.php
- library/Director/Web/Table/ObjectsTableSetMembers.php
- library/Director/Web/Table/ServiceTemplateUsageTable.php
- library/Director/Web/Table/TemplateUsageTable.php
- phpstan-baseline.neon
Services under service set is shown under `setmembers` of `TemplateUsageTable`. And objects shows only services which do not belong to service set. This must solve the inconsistent number of objects problem.
ref/IP/33703
> Add `setmembers` summyary line to `TemplateUsageTable` 

- library/Director/Web/Controller/ObjectsController.php
> Fix editing of multi-selected services with same name

- application/clicommands/KickstartCommand.php
Updates the comment in KickstartCommand to match the exit code functionality.
Mentioned in issue #2772
> Provide explanation for all exit codes

- library/Director/Objects/IcingaObjectGroups.php
> Fix db type error, when hostgroup is accidentially interpreted as integer

- .github/workflows/php.yml
- application/forms/IcingaObjectFieldForm.php
- library/Director/Field/FormFieldSuggestion.php
- library/Director/Test/BaseTestCase.php
- library/Director/Test/IcingaObjectTestCase.php
- library/Director/Test/SyncTest.php
- phpstan-baseline.neon
- phpstan.neon
- test/php/library/Director/Form/IcingaObjectFieldFormTest.php
- test/php/library/Director/IcingaConfig/StateFilterTest.php
- test/php/library/Director/Objects/HostGroupMembershipResolverTest.php
- test/php/library/Director/Objects/IcingaCommandTest.php
- test/php/library/Director/Objects/IcingaHostTest.php
- test/php/library/Director/Objects/IcingaNotificationTest.php
- test/php/library/Director/Objects/IcingaServiceSetTest.php
- test/php/library/Director/Objects/IcingaServiceTest.php
- test/php/library/Director/Objects/IcingaTemplateResolverTest.php
- test/php/library/Director/Objects/IcingaTimePeriodTest.php
- test/php/library/Director/Resolver/TemplateTreeTest.php
Other available fields should be suggested when no check command has been chosen for service template.
fixes #2826, #2815
> Fix form field suggestions

- application/forms/IcingaDependencyForm.php
- library/Director/Objects/IcingaDependency.php
Earlier the director did not support the rendering of service custom variables for Parent Service in Dependencies form. Here, this issue is fixed.
fixes #2289
>  Support the rendering of service custom variable in Dependencies form

- library/Director/Objects/DirectorActivityLog.php
- library/Director/Objects/IcingaServiceSet.php
- library/Director/Web/Widget/ActivityLogInfo.php
All the services which were under the service set when it was deleted must be restored when it is restored from activity log.
dependent on PR: #2418 
fix #1065
> Restore services of service set on restoring service set.

- schema/pgsql-migrations/upgrade_188.sql
- schema/pgsql.sql
Unique constraints `import_row_modifier_prio` and `service_branch_object_name` are only present in PostgreSQL and not in MySQL. But the constraints needs to be consistent across databases.
fixes #2270
> Make unique constraints consistent across databases

- doc/16-Fields-example-SNMP.md
Hi,
I was reading the Icinga Director documentation and spotted a typo in the [Data Fields example: SNMP](https://icinga.com/docs/icinga-director/latest/doc/16-Fields-example-SNMP/) page. I've included a patch to fix the typo.
Thanks!
> Fix typo in SNMP Data Fields example documentation

- library/Director/Objects/IcingaObjectMultiRelations.php
> IcingaObjectMultiRelations: Set property `modified` to false when loaded from DB

- library/Director/Db/Branch/BranchedObject.php
Sync rules created for import sources, importing objects with boolean properties,  throws `SQLSTATE` error as shown in the screenshot below.
The reason for this is because the preview creates temporary branched objects by importing the objects' properties to check for the modifications. And the boolean properties, were not transformed to `y` or `n` (which is the supported datatype for boolean (`ENUM('y','n')`) to store in the database) before the temporary object is created.
fixes ref/IP/53248
> Fix sync rule preview in case of boolean properties

- library/Director/PropertyModifier/PropertyModifierGetHostByName.php
> PropertyModifierGetHostByName: Fix inet_pton unrecognized address error

- library/Director/DirectorObject/Automation/Basket.php
> Basket::setObjects: Reset `$chosenObjects` property only if the given objects is empty

- application/forms/IcingaMultiEditForm.php
> IcingaMultiEditForm: Fix editing custom vars with space in their name

- application/forms/IcingaCloneObjectForm.php
The cloned host must also have services and service sets that are under the original host.
fixes #2897
> IcingaCloneObjectForm: Fix cloning of hosts in director branches

- application/controllers/TimeperiodController.php
This adds the missing "hasBasketSupport" for TimePeriodController which allows to add the TimePeriod to specific baskets.
Fixes [Missing "Add to basket" for TimePeriods #2542 ](https://github.com/Icinga/icingaweb2-module-director/issues/2542)
> Add hasBasketSupport for TimePeriods

- library/Director/Objects/DirectorDatafield.php
- library/Director/ProvidedHook/Icingadb/CustomVarRenderer.php
- library/Director/ProvidedHook/Monitoring/CustomVarRenderer.php
- register-hooks.php
resolves #2239
requires https://github.com/Icinga/icingaweb2/pull/4614 or https://github.com/Icinga/icingadb-web/pull/467
> Enrich custom variable lists in monitoring and icingadb details

- application/forms/IcingaCloneObjectForm.php
- library/Director/Web/Controller/ObjectController.php
> Allow cloning of service sets in branches

- library/Director/Web/Form/PropertyTableSortForm.php
- library/Director/Web/Table/PropertymodifierTable.php
- library/Director/Web/Table/SyncpropertyTable.php
It's incompatible with gipfl`s…
fixes #2935
> PropertyTableSortForm: Don't use ipl`s CSRF counter measure

- application/forms/IcingaHostForm.php
> IcingaHostForm: Fix crashing of form for invalid check command

- schema/mysql-migrations/upgrade_188.sql
- schema/mysql.sql
- See https://github.com/Icinga/icingaweb2-module-director/issues/2885 (and my comment on the issue).
- Fix MySQL-8.4 nonstandard foreign keys deprecation.
> [!IMPORTANT]  
> I have no previous MySQL experience. This is working queries I generated with the help of AI, and tested locally that it works for my setup using the latest latest MySQL (version 8.4.3) while setting up the Director module on Icinga Web 2 for the first time. Someone with more experience in MySQL should review it, and ideally merge a fix ASAP because it leads to a broken setup for new users (and whoever upgrades MySQL to 8.4+) with a essentially useless SQL error message for a user, which I found no reference to when searching the documentation or online.
The main error the user would normally see looks something …
> #2885 Fix MySQL8.4 nonstandard foreign keys deprecation

- schema/mysql-migrations/upgrade_188.sql
> upgrade_188: Remove entries with duplicate checksums in director_activity_log

- application/forms/DeployFormsBug7530.php
Since PHP 8.0 passing of null to strlen is deprecated and hence must be avoided.
> DeployFormsBug7530: Do not pass null values to `strlen`
